/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientearduino;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Feltrin
 */
public class Cliente extends javax.swing.JFrame implements Runnable {

  /**
   * Creates new form Cliente
   */
  ClienteArduino client = new ClienteArduino();
  Thread busca = new Thread(this);
  
  public Cliente() {
    initComponents();
    try {
      client.ClienteIP();
    } catch (Exception ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
    busca.start();
  }

  public void run(){
   while(true){
      try {
        //System.out.println("Thread");
        String status= client.ClienteBusca("STATUS");
        String Booleana;
        boolean TorF;
        Booleana=status;//.substring(status.indexOf("L")+1, status.indexOf("A"));
        TorF=Boolean.parseBoolean(Booleana);
        if(TorF){
          jTBAlarme.setSelected(TorF);
          jTBAlarme.setText("Alarme: Ligado");
        }else{
          jTBAlarme.setSelected(TorF);
          jTBAlarme.setText("Alarme: Desligado");
        }
        Thread.sleep(3000);
      } catch (Exception ex) {
        Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jEditorPane1 = new javax.swing.JEditorPane();
    jLabel1 = new javax.swing.JLabel();
    jTBAlarme = new javax.swing.JToggleButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jPFSenha = new javax.swing.JPasswordField();
    jBPorta = new javax.swing.JButton();
    jMBWebHouse = new javax.swing.JMenuBar();
    jMWebHouse = new javax.swing.JMenu();
    jMIHouse = new javax.swing.JMenuItem();
    jMISair = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMIConf = new javax.swing.JMenuItem();
    jMISobre = new javax.swing.JMenuItem();

    jScrollPane1.setViewportView(jEditorPane1);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("AutoSeg");
    setResizable(false);

    jLabel1.setText("Senha:");

    jTBAlarme.setText("Alarme: Desligado");
    jTBAlarme.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTBAlarmeActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    jLabel3.setText("AutoSeg");

    jBPorta.setText("Abrir Porta");
    jBPorta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBPortaActionPerformed(evt);
      }
    });

    jMWebHouse.setText("AutoSeg");

    jMIHouse.setText("Segurança");
    jMWebHouse.add(jMIHouse);

    jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
    jMISair.setText("Sair");
    jMISair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISairActionPerformed(evt);
      }
    });
    jMWebHouse.add(jMISair);

    jMBWebHouse.add(jMWebHouse);

    jMenu2.setText("Sistema");

    jMIConf.setText("Configuração");
    jMIConf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMIConfActionPerformed(evt);
      }
    });
    jMenu2.add(jMIConf);

    jMISobre.setText("Sobre");
    jMISobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISobreActionPerformed(evt);
      }
    });
    jMenu2.add(jMISobre);

    jMBWebHouse.add(jMenu2);

    setJMenuBar(jMBWebHouse);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jTBAlarme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(92, 92, 92)
            .addComponent(jLabel3)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jBPorta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(jLabel3)
        .addGap(55, 55, 55)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addComponent(jLabel1))
          .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(33, 33, 33)
        .addComponent(jBPorta)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addComponent(jTBAlarme)
        .addGap(44, 44, 44))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jTBAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBAlarmeActionPerformed
    // TODO add your handling code here:
    if(jPFSenha.getText().equals("UNIFRA")){
        if(jTBAlarme.isSelected()){
            try {
              client.ClienteAcao("L A");
            } catch (Exception ex) {
              Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
              client.ClienteAcao("D A");
            } catch (Exception ex) {
              Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jPFSenha.setText(null);
   }
  }//GEN-LAST:event_jTBAlarmeActionPerformed

  private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
    // TODO add your handling code here:
   dispose();
   System.exit(0);
  }//GEN-LAST:event_jMISairActionPerformed

  private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
    // TODO add your handling code here:
    Sobre formSobre = new Sobre();
    formSobre.setVisible(true);
    dispose();
    busca.stop();
  }//GEN-LAST:event_jMISobreActionPerformed

  private void jMIConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfActionPerformed
    // TODO add your handling code here:
    Configuracao formConf = new Configuracao();
    formConf.setVisible(true);
    dispose();
    busca.stop();
  }//GEN-LAST:event_jMIConfActionPerformed

  private void jBPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPortaActionPerformed
    try {
      if(client.ClienteBusca(jPFSenha.getText()).equals("Erro")){
          JOptionPane.showMessageDialog(this,"Senha Incorreta!");
      }else{
        JOptionPane.showMessageDialog(this,"Entrada Permitida!");
      }
      jPFSenha.setText(null);
    } catch (Exception ex) {
      Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jBPortaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Cliente().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBPorta;
  private javax.swing.JEditorPane jEditorPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JMenuBar jMBWebHouse;
  private javax.swing.JMenuItem jMIConf;
  private javax.swing.JMenuItem jMIHouse;
  private javax.swing.JMenuItem jMISair;
  private javax.swing.JMenuItem jMISobre;
  private javax.swing.JMenu jMWebHouse;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JPasswordField jPFSenha;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JToggleButton jTBAlarme;
  // End of variables declaration//GEN-END:variables

  private void sleep(int i) {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  }

}
