/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientearduino;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Feltrin
 */
public class Configuracao extends javax.swing.JFrame {

  /**
   * Creates new form Configuracao
   */
  ClienteArduino cliente = new ClienteArduino();
  
  public Configuracao(){
    initComponents();  
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFTFIP = new javax.swing.JFormattedTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jTFDDNS = new javax.swing.JTextField();
    jBSalvarIP = new javax.swing.JButton();
    jTFPorta = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jBSalvarDDNS = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMIHouse = new javax.swing.JMenuItem();
    jMISair = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMIConf = new javax.swing.JMenuItem();
    jMISobre = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("AutoSeg");
    setResizable(false);

    try {
      jFTFIP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    jFTFIP.setText("000.000.000.000  ");
    jFTFIP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFTFIPActionPerformed(evt);
      }
    });

    jLabel1.setText("IP:");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("Configurações de Rede");

    jLabel3.setText("DDNS:");

    jBSalvarIP.setText("Salvar Porta e IP");
    jBSalvarIP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBSalvarIPActionPerformed(evt);
      }
    });

    jLabel4.setText("Porta:");

    jBSalvarDDNS.setText("Salvar DDNS e Porta");
    jBSalvarDDNS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jBSalvarDDNSActionPerformed(evt);
      }
    });

    jMenu1.setText("AutoSeg");

    jMIHouse.setText("Segurança");
    jMIHouse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMIHouseActionPerformed(evt);
      }
    });
    jMenu1.add(jMIHouse);

    jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
    jMISair.setText("Sair");
    jMISair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISairActionPerformed(evt);
      }
    });
    jMenu1.add(jMISair);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Sistema");

    jMIConf.setText("Configuração");
    jMIConf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMIConfActionPerformed(evt);
      }
    });
    jMenu2.add(jMIConf);

    jMISobre.setText("Sobre");
    jMISobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISobreActionPerformed(evt);
      }
    });
    jMenu2.add(jMISobre);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(jLabel2))
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel1)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jFTFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTFDDNS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTFPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 11, Short.MAX_VALUE)
            .addComponent(jBSalvarIP)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
            .addComponent(jBSalvarDDNS)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addGap(46, 46, 46)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTFPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jFTFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTFDDNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(39, 39, 39)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jBSalvarIP)
          .addComponent(jBSalvarDDNS))
        .addContainerGap(61, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jMIConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMIConfActionPerformed

  private void jMIHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIHouseActionPerformed
    // TODO add your handling code here:
    Cliente formHouse = new Cliente();
    formHouse.setVisible(true);
    dispose();
  }//GEN-LAST:event_jMIHouseActionPerformed

  private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
    // TODO add your handling code here:
    Sobre formSobre = new Sobre();
    formSobre.setVisible(true);
    dispose();
  }//GEN-LAST:event_jMISobreActionPerformed

  private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
    // TODO add your handling code here:
    dispose();
    System.exit(0);
  }//GEN-LAST:event_jMISairActionPerformed

  private void jFTFIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jFTFIPActionPerformed

  private void jBSalvarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarIPActionPerformed
    // TODO add your handling code here:
    String porta = jTFPorta.getText();
    String IP = jFTFIP.getText();
    try {
      cliente.ClienteConfigIP(IP, porta);
    } catch (Exception ex) {
      Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
    }
    System.out.println(IP+"----"+porta);
  }//GEN-LAST:event_jBSalvarIPActionPerformed

  private void jBSalvarDDNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarDDNSActionPerformed
    // TODO add your handling code here:
    String porta = jTFPorta.getText();
    String DDNS = jTFDDNS.getText();
    try {
      cliente.ClienteConfigDDNS(DDNS, porta);
    } catch (Exception ex) {
      Logger.getLogger(Configuracao.class.getName()).log(Level.SEVERE, null, ex);
    }
    System.out.println(DDNS+"----"+porta);
  }//GEN-LAST:event_jBSalvarDDNSActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Configuracao().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jBSalvarDDNS;
  private javax.swing.JButton jBSalvarIP;
  private javax.swing.JFormattedTextField jFTFIP;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenuItem jMIConf;
  private javax.swing.JMenuItem jMIHouse;
  private javax.swing.JMenuItem jMISair;
  private javax.swing.JMenuItem jMISobre;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JTextField jTFDDNS;
  private javax.swing.JTextField jTFPorta;
  // End of variables declaration//GEN-END:variables
}
