/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientearduino;

/**
 *
 * @author Feltrin
 */
public class Sobre extends javax.swing.JFrame {

  /**
   * Creates new form Sobre
   */
  public Sobre() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMIHouse = new javax.swing.JMenuItem();
    jMISair = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMIConf = new javax.swing.JMenuItem();
    jMISobre = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("AutoSeg");
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
    jLabel1.setText("AutoSeg");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.setText("Versão: Feira das Profissões\n    Ciência da Computação\n    UNIFRA - 2013\n\nDesenvolvedores:\n\tPéricles Feltrin\n\tSérgio Righi\n\tLucas Bastos\n\tMarcos Righi\n\tNicoli Rodrigues");
    jScrollPane1.setViewportView(jTextArea1);

    jMenu1.setText("AutoSeg");

    jMIHouse.setText("Segurança");
    jMIHouse.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMIHouseActionPerformed(evt);
      }
    });
    jMenu1.add(jMIHouse);

    jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
    jMISair.setText("Sair");
    jMISair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISairActionPerformed(evt);
      }
    });
    jMenu1.add(jMISair);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Sistema");

    jMIConf.setText("Configuração");
    jMIConf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMIConfActionPerformed(evt);
      }
    });
    jMenu2.add(jMIConf);

    jMISobre.setText("Sobre");
    jMISobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMISobreActionPerformed(evt);
      }
    });
    jMenu2.add(jMISobre);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(76, 76, 76)
        .addComponent(jLabel1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
    // TODO add your handling code here:
    dispose();
    System.exit(0);
  }//GEN-LAST:event_jMISairActionPerformed

  private void jMIHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIHouseActionPerformed
    // TODO add your handling code here:
    Cliente formHouse = new Cliente();
    formHouse.setVisible(true);
    dispose();
  }//GEN-LAST:event_jMIHouseActionPerformed

  private void jMIConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConfActionPerformed
    // TODO add your handling code here:
    Configuracao formConf = new Configuracao();
    formConf.setVisible(true);
    dispose();
  }//GEN-LAST:event_jMIConfActionPerformed

  private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMISobreActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Sobre().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenuItem jMIConf;
  private javax.swing.JMenuItem jMIHouse;
  private javax.swing.JMenuItem jMISair;
  private javax.swing.JMenuItem jMISobre;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
